name: 'CI-master-development'

on:
  repository_dispatch:
    types: do-master-development-ci

jobs:
  master-build:
    runs-on: ubuntu-latest
    timeout-minutes: 420 # default 360
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: '1'
        ref: 'master'
    - name: Install Java 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'
        java-package: jdk
        architecture: x64
    - name: Cache gradle dependencies
      uses: actions/cache@v1
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-gradle-cache-master-v1
        restore-keys: |
          ${{ runner.os }}-gradle-cache-master-v1
    - name: 'Install dependencies'
      run: |
        ./ci-install-dependencies.sh
    - name: 'Print dependencies version'
      run: |
        ./ci-print-dependencies-version.sh
    - name: 'CI Build Command'
      timeout-minutes: 20
      env:
        TEST_ENVIRONMENT: 'development'
      run: |
        ./ci-build.sh
    - name: Archive acceptance test results
      uses: actions/upload-artifact@v1
      if: ${{ always() }}
      with:
        name: acceptance-test-result
        path: acceptance-test/build/reports/tests
    - name: Archive acceptance test screenshots
      uses: actions/upload-artifact@v1
      if: ${{ always() }}
      with:
        name: acceptance-test-screenshots
        path: acceptance-test/screenshots